#
#  Makefile for phyLayer
#
#  ** This file was automatically generated by the command:
#  opp_makemake -f -N -b /home/fasika/mixim/trunk -c /home/fasika/mixim/trunk/omnetppconfig -I/home/fasika/mixim/trunk/include -L/home/fasika/mixim/trunk/lib -lmixim
#

# Name of target to be created (-o option)
TARGET = New

# User interface (uncomment one) (-u option)
USERIF_LIBS=$(CMDENV_LIBS)
#USERIF_LIBS=$(TKENV_LIBS)

# .ned or .h include paths with -I
INCLUDE_PATH= -I../../include

# misc additional object and library files to link
EXTRA_OBJS=

# object files from other directories to link with (wildcard needed to prevent "no such file *.o" errors)
EXT_DIR_OBJS=

# time stamps of other directories (used as dependency)
EXT_DIR_TSTAMPS= ../../include/.tstamp

# Additional libraries (-L option -l option)
LIBS= -L../../lib -lmixim

#------------------------------------------------------------------------------
# Import generic settings from ../../omnetppconfig
include ../../omnetppconfig

MSGCOPTS= $(INCLUDE_PATH)

#------------------------------------------------------------------------------

# subdirectories to recurse into
SUBDIRS= 

# object files in this directory
OBJS=  MacLayer.o PhyLayer.o

# header files generated (from msg files)
GENERATEDHEADERS= 

#------------------------------------------------------------------------------

$(TARGET): $(OBJS) $(EXTRA_OBJS) $(EXT_DIR_TSTAMPS) Makefile
	$(CXX) $(LDFLAGS) $(OBJS) $(EXTRA_OBJS) $(EXT_DIR_OBJS) $(LIBS) $(OMNETPP_LIBS) -o $(TARGET)
	echo>.tstamp

$(OBJS) : $(GENERATEDHEADERS)


purify: $(OBJS) $(EXTRA_OBJS) $(EXT_DIR_TSTAMPS) Makefile
	purify $(CXX) $(LDFLAGS) $(OBJS) $(EXTRA_OBJS) $(EXT_DIR_OBJS) $(LIBS) -L$(OMNETPP_LIB_DIR) $(KERNEL_LIBS) $(USERIF_LIBS) $(SYS_LIBS_PURE) -o $(TARGET).pure

$(EXT_DIR_TSTAMPS):
	@echo
	@echo Error: $@ does not exist.
	@echo This means that at least the above dependency directory has not been built.
	@echo Maybe you need to do a top-level make?
	@echo
	@exit 1

.PHONY: subdirs $(SUBDIRS)

subdirs: $(SUBDIRS)

MacLayer.o: MacLayer.cc
	$(CXX) -c $(COPTS) MacLayer.cc

PhyLayer.o: PhyLayer.cc
	$(CXX) -c $(COPTS) PhyLayer.cc


#doc: neddoc doxy

#neddoc:
#	opp_neddoc -a

#doxy: doxy.cfg
#	doxygen doxy.cfg

generateheaders: $(GENERATEDHEADERS)
	for i in $(SUBDIRS); do (cd $$i && $(MAKE) generateheaders) || exit 1; done

clean:
	rm -f $(TARGET)$(EXE_SUFFIX)
	rm -f *.o *_n.cc *_n.h *_m.cc *_m.h .tstamp
	rm -f *.vec *.sca
	for i in $(SUBDIRS); do (cd $$i && $(MAKE) clean); done

depend:
	$(MAKEDEPEND) $(INCLUDE_PATH) -- *.cc
	# $(MAKEDEPEND) $(INCLUDE_PATH) -fMakefile.in -- *.cc
	for i in $(SUBDIRS); do (cd $$i && $(MAKE) depend) || exit 1; done

makefiles:
	# recreate Makefile
	opp_makemake -f  -N -b /home/fasika/mixim/trunk -c /home/fasika/mixim/trunk/omnetppconfig -I/home/fasika/mixim/trunk/include -L/home/fasika/mixim/trunk/lib -lmixim 
	for i in $(SUBDIRS); do (cd $$i && $(MAKE) makefiles) || exit 1; done

makefile-ins:
	# recreate Makefile.in
	opp_makemake -f -m  -N -b /home/fasika/mixim/trunk -c /home/fasika/mixim/trunk/omnetppconfig -I/home/fasika/mixim/trunk/include -L/home/fasika/mixim/trunk/lib -lmixim 
	for i in $(SUBDIRS); do (cd $$i && $(MAKE) makefile-ins) || exit 1; done

# "re-makemake" and "re-makemake-m" are deprecated, historic names of the above two targets
re-makemake: makefiles
re-makemake-m: makefile-ins


# DO NOT DELETE THIS LINE -- make depend depends on it.
MacLayer.o: MacLayer.cc \
  MacLayer.h \
  ../../include/MacToPhyInterface.h \
  ../../include/MacToPhyControlInfo.h \
  ../../include/Signal_.h \
  ../../include/MacPkt_m.h \
  ../../include/ChannelState.h \
  ../../include/PhyUtils.h \
  ../../include/AnalogueModel.h \
  ../../include/Move.h \
  ../../include/Coord.h \
  ../../include/BaseUtility.h \
  ../../include/ImNotifiable.h \
  ../../include/FWMath.h \
  ../../include/BaseModule.h \
  ../../include/FindModule.h
PhyLayer.o: PhyLayer.cc \
  PhyLayer.h \
  ../../include/BasePhyLayer.h \
  ../../include/ChannelAccess.h \
  ../../include/DeciderToPhyInterface.h \
  ../../include/MacToPhyInterface.h \
  ../../include/AnalogueModel.h \
  ../../include/Decider.h \
  ../../include/ChannelInfo.h \
  ../../include/BaseWorldUtility.h \
  ../../include/MacPkt_m.h \
  ../../include/BaseModule.h \
  ../../include/Move.h \
  ../../include/BaseConnectionManager.h \
  ../../include/ImNotifiable.h \
  ../../include/FindModule.h \
  ../../include/Coord.h \
  ../../include/BaseUtility.h \
  ../../include/FWMath.h \
  ../../include/NicEntry.h \
  ../../include/AirFrame.h \
  ../../include/AirFrame_m.h \
  ../../include/Signal_.h \
  ../../include/ChannelState.h \
  ../../include/PhyUtils.h \
  ../../include/ChannelSenseRequest_m.h
